title: xiangui's Homepage
page-top-title: wentao yao
top-section-bg-text: experience hardness, achieve success
home-subtitle: WenTao Yao&ensp;|&ensp;姚文涛
copyright-text: '&copy; xiangui 2023-2025. All Rights Reserved.'
# site_name: "WenTao Yao"
# site_description: "Electronic Science and Technology/master"
# email: "b22020029@njupt.edu.cn"