title: xiangui's Homepage
page-top-title: xiangui
top-section-bg-text: Be what you wanna be
home-subtitle: xiangui&ensp;|&ensp;上杉绘梨衣
copyright-text: '&copy; xiangui 2023-2025. All Rights Reserved.'
site_name: "WenTao Yao"
site_description: "Electronic Science and Technology/master"
email: "b22020029@njupt.edu.cn"